"""Force AAF alignment fix v2.

Root cause of facing-opposite / one standing one lying:
Ultimate AAF Patch Override XMLs use defaults offset="0,50,180".
That 180 yaw makes actors face opposite directions when original
position IDs (Atomic Kissing, etc.) are still started by HotC/AAF.

Fix:
- Disable Ultimate + Extended (UAP override approach)
- Enable One Patch (overwrites same-named positionData with good offsets)
- Keep Leito/Crazy patch enabled and winning
- Keep Atomic Muscle skeletons hidden
- Keep actor scale assist in AAF_settings.ini
"""
from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

MO2 = Path(r"C:\Users\Ray\AppData\Local\ModOrganizer\Fallout 4")
MODS = MO2 / "mods"
MODLIST = MO2 / "profiles" / "Default" / "modlist.txt"
MOD_DATA = Path(r"C:\Software Projects\Fallout4Mod\mod_manager\mod_data.json")
AAF_SETTINGS = MODS / "Advanced Animation Framework" / "AAF" / "AAF_settings.ini"

DISABLE = {
    "Ultimate AAF Patch",
    "Extended AAF Patch",
    "Patch for animations (SquirtCum Effects, cum overlays, stages, fixes) 11.0",
    "LooksMenu v1-7-0-2",
    "Mod Configuration Menu 1.43",
    "Address Library",
}

ENABLE = {
    "AAF - The One Patch to Bang Them All",
    "AAF patches for Leito and Crazy animations",
    "Advanced Animation Framework",
    "ZeX - ZaZ Extended Skeleton",
    "BodyTalk",
    "Atomic Lust",
    "FO4 Animations by Leito",
    "Four-Play Animations by Crazy6987",
    "SavageCabbages Animation Pack",
    "BP70 Fallout 4 Sex Animations 2.3",
    "Address Library - All In One",
    "LooksMenu v1-7-0-3",
    "Mod Configuration Menu 1.11.221",
}

# These must beat base anim packs (higher in modlist = earlier in file)
PRIORITY_HIGH_FIRST = [
    "AAF patches for Leito and Crazy animations",
    "AAF - The One Patch to Bang Them All",
]

ANIM_PACKS = [
    "RZF4S_",
    "SAM Enhanced Animations",
    "BP70 Fallout 4 Sex Animations 2.3",
    "SavageCabbages Animation Pack",
    "Animated_Fannies__",
    "FO4 Animations by Leito",
    "Four-Play Animations by Crazy6987",
    "AAF Vanilla-Kinky-Creatures Sex Animation Themes",
    "Atomic Lust",
]


def ensure_atomic_muscle_skeleton_hidden() -> None:
    am = MODS / "Atomic Muscle" / "Meshes" / "Actors" / "Character" / "CharacterAssets"
    if not am.exists():
        print("Atomic Muscle CharacterAssets missing")
        return
    for name in (
        "skeleton.nif",
        "skeleton.hkx",
        "skeleton_faceBones.nif",
        "skeleton_female_faceBones.nif",
    ):
        src = am / name
        dst = am / f"{name}.disabled"
        if src.exists():
            if dst.exists():
                dst.unlink()
            src.rename(dst)
            print(f"hid Atomic Muscle {name}")
        elif dst.exists():
            print(f"already hid Atomic Muscle {name}")


def apply_flags_and_order() -> None:
    shutil.copy2(MODLIST, MODLIST.with_suffix(".txt.bak_align_v2"))
    lines = MODLIST.read_text(encoding="utf-8").splitlines()

    header: list[str] = []
    stars: list[str] = []
    managed: list[tuple[str, str]] = []

    for line in lines:
        if line.startswith("*"):
            stars.append(line)
        elif line[:1] in "+-" and len(line) > 1:
            managed.append((line[0], line[1:]))
        else:
            if not managed:
                header.append(line)
            elif line.strip():
                # stray
                pass

    by_name = {n: p for p, n in managed}
    order = [n for _, n in managed]

    # Force flags
    for n in DISABLE:
        if n in by_name:
            by_name[n] = "-"
    for n in ENABLE:
        if n in by_name:
            by_name[n] = "+"

    # Pull priority patches to just above anim packs (or near top of AAF block)
    for n in PRIORITY_HIGH_FIRST + ANIM_PACKS:
        if n in order:
            order.remove(n)

    # Find insertion point: before first remaining anim-ish or after Clean My Settlement
    insert_at = 0
    for i, n in enumerate(order):
        if n.startswith("Commonwealth") or n.startswith("Hookers") or n == "LLFP":
            insert_at = i
            break
    else:
        # put after settlements if present
        for i, n in enumerate(order):
            if "Scrap scrap" in n or "Weapons Level List" in n:
                insert_at = i + 1
                break

    block = [n for n in PRIORITY_HIGH_FIRST + ANIM_PACKS if n in by_name]
    order = order[:insert_at] + block + order[insert_at:]

    out = header[:] if header else ["# This file was automatically generated by Mod Organizer."]
    for n in order:
        out.append(f"{by_name.get(n, '+')}{n}")
    out.extend(stars)
    MODLIST.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote modlist with One Patch above anim packs ({len(order)} mods)")


def patch_aaf_settings() -> None:
    if not AAF_SETTINGS.exists():
        print("AAF_settings.ini missing")
        return
    raw = AAF_SETTINGS.read_text(encoding="utf-8", errors="replace")
    bak = AAF_SETTINGS.with_suffix(".ini.bak_align")
    if not bak.exists():
        bak.write_text(raw, encoding="utf-8")

    def set_key(text: str, key: str, value: str) -> str:
        pattern = re.compile(rf"^(\s*{re.escape(key)}\s*=\s*).*$", re.M)
        if pattern.search(text):
            return pattern.sub(rf"\g<1>{value}", text, count=1)
        return text

    new = set_key(raw, "scale_actors_for_animations", "true")
    new = set_key(new, "enforce_race_scale", "false")
    AAF_SETTINGS.write_text(new, encoding="utf-8")
    print("AAF_settings: scale_actors_for_animations=true")


def update_mod_data() -> None:
    if not MOD_DATA.exists():
        return
    data = json.loads(MOD_DATA.read_text(encoding="utf-8-sig"))
    for n in DISABLE:
        if n in data:
            data[n]["enabled"] = False
    for n in ENABLE:
        if n in data:
            data[n]["enabled"] = True
    MOD_DATA.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def verify() -> None:
    print("\n=== VERIFY flags / order ===")
    for line in MODLIST.read_text(encoding="utf-8").splitlines():
        if any(
            x in line
            for x in (
                "One Patch",
                "Ultimate AAF",
                "Extended AAF",
                "Patch for animations",
                "AAF patches for Leito",
                "Atomic Lust",
                "FO4 Animations",
                "ZeX",
                "Atomic Muscle",
            )
        ):
            print(line)

    print("\n=== positionData winners ===")
    targets = [
        "Atomic Lust_positionData.xml",
        "Leito_positionData.xml",
        "SavageCabbage_positionData.xml",
        "rxl_bp70_anims_positionData.xml",
        "Four-Play_Animations_by_Crazy_positionData.xml",
    ]
    for t in targets:
        for line in MODLIST.read_text(encoding="utf-8").splitlines():
            if line.startswith("+"):
                name = line[1:]
                p = MODS / name / "AAF" / t
                if p.exists():
                    print(f"{t} <= {name}")
                    break

    sk_am = (
        MODS
        / "Atomic Muscle"
        / "Meshes"
        / "Actors"
        / "Character"
        / "CharacterAssets"
        / "skeleton.nif"
    )
    print(f"\nAtomic Muscle skeleton active? {sk_am.exists()}")
    for line in MODLIST.read_text(encoding="utf-8").splitlines():
        if line.startswith("+"):
            name = line[1:]
            sk = (
                MODS
                / name
                / "Meshes"
                / "Actors"
                / "Character"
                / "CharacterAssets"
                / "skeleton.nif"
            )
            if sk.exists():
                print(f"skeleton.nif winner: {name}")
                break


def main() -> None:
    print("1) Hide Atomic Muscle skeletons")
    ensure_atomic_muscle_skeleton_hidden()
    print("2) Switch to One Patch stack (disable Ultimate)")
    apply_flags_and_order()
    print("3) AAF settings")
    patch_aaf_settings()
    print("4) mod_data.json")
    update_mod_data()
    verify()
    print(
        "\nIMPORTANT: Fully close Fallout 4 AND Mod Organizer, reopen MO2, then launch."
    )


if __name__ == "__main__":
    main()
