import json

# List your preferred mod order here (folder names as they appear in mod_data.json)
preferred_order = [
    "DLC: Automatron",
    "DLC: Wasteland Workshop",
    "DLC: Far Harbor",
    "DLC: Contraptions Workshop",
    "DLC: Vault-Tec Workshop",
    "DLC: Nuka-World",
    "DLC: Ultra High Resolution Texture Pack",
    "Creation Club: ccbgsfo4006-pipboychrome",
    "Creation Club: ccbgsfo4044-HellfirePowerArmor",
    "Creation Club: ccbgsfo4015-X02",
    "Creation Club: ccbgsfo4116-HeavyFlamer",
    "Creation Club: ccbgsfo4110-WS_Enclave",
    "Creation Club: ccbgsfo4096-AS_Enclave",
    "Creation Club: ccbgsfo4070-Halloween",
    "Creation Club: ccbgsfo4001-vsuit",
    "Creation Club: ccbgsfo4046-TesCan",
    "Creation Club: ccbgsfj0403-Grenade",
    "Creation Club: ccmtof0401-Remnants",
    "Unmanaged: knightmare batman",
    "Unmanaged: batman beyond",
    "Unmanaged: cheatterminal",
    "Unmanaged: crysis2nanosuit",
    "Unmanaged: horsesweothorne",
    "Unmanaged: modern firearms",
    # 1) Core Frameworks & Engine Fixes
    "Address Library - All In One",
    "Address Library",
    "Buffout 4",
    "Unofficial Fallout 4 Patch",
    "Mod Configuration Menu 1.11.221",
    "Mod Configuration Menu 1.43",
    # 2) Animation & Body Frameworks
    "Advanced Animation Framework",
    "ZeX - ZaZ Extended Skeleton",
    "BodySlide and Outfit Studio -",
    # 3) Body Frameworks & Physics
    "Caliente's Beautiful Bodies Enhancer -CBBE-",
    "BodyTalk",
    "Atomic Muscle",
    "Sam BodySlide Output",
    "MTM 3B OCBP - OCBPC Physics and Collision Preset",
    "Toned and Shapely Body for CBBE and 3BA Vagina Add-on",
    # 4) Textures, Skins, & Face Morphs
    "RealVagCBBE",
    "Muscular Body",
    "ADDON_Body_Textures_With_Detailed_Vagina",
    "Younger Male Face Texture",
    "BodyTriangleEnhancer",
    "High Res DLC Black Face Fix",
    # 5) NPC Changes & Hair
    "Beautiful Female Settlers",
    "Beautiful Female Enemies V. 2.0",
    "MyCleanRaiders_CBBE1.0",
    "Lots More Male Hairstyles v. 1.21 - Fix",
    "Lots More Female Hairstyles v. 1.33",
    "Ponytail Hairstyles by Azar - BA2",
    "Looks Menu Customization Compendium",
    "LooksMenu v1-7-0-2",
    "LooksMenu v1-7-0-3",
    # 6) AAF Theme Packs & Adult Frameworks
    "SexAttributes",
    "AAF_FamilyPlanningEnhanced_",
    "AAF_SEU_V",
    "AAF_SCRS",
    "AAF - The One Patch to Bang Them All",
    "Atomic Lust",
    "AAF Vanilla-Kinky-Creatures Sex Animation Themes",
    "Four-Play Animations by Crazy6987",
    "Animated_Fannies__",
    "FO4 Animations by Leito",
    "AAF patches for Leito and Crazy animations",
    "SavageCabbages Animation Pack",
    "BP70 Fallout 4 Sex Animations 2.3",
    "SAM Enhanced Animations",
    "RZF4S_",
    "Dynamic Cumshots",
    "CumOverlays v",
    "Patch for animations (SquirtCum Effects, cum overlays, stages, fixes) 11.0",
    "Extended AAF Patch",
    "Ultimate AAF Patch",
    "Commonwealth Moisturizer",
    "Hookers of the Commonwealth (HotC) - v.0.99h",
    "LLFP",
    "Nude Male Cut Erect",
    # 7) Armor, Clothing, & Weapons
    "NanoSuit",
    "Black and Red Vaultsuit_FULL_Male and Female",
    "Black Road Leathers",
    "Cronen Squall - Main",
    "JensenArmor",
    "Stealth Glasses",
    "AS Vektor Commonwealth Version",
    "RU556 - Assault Rifle",
    "Smith and Wesson 500- REDUX beta",
    "Combined Arms - 1.0",
    "Accuracy International AX50",
    "Tavor X95",
    "MG42",
    "FN P90",
    "Bolt Actions of the Wasteland",
    "HK G11 K2",
    "Mk 23 SOCOM - 1.0 - MAIN",
    "1. SR-25 - Main CN",
    "FACTOR ENG (FULL)",
    "155mm Howitzer M1 4K New",
    "2. Glock family - Main NO TR",
    "Scar Family - Main NO TR",
    "Desert Eagle",
    "Desert Eagle Silencer 1.4",
    "R8 Revolver 4K",
    "Remington 700",
    "Kendall Ballistics Karma",
    "Stahl Arms STA-20 10mm Pistol",
    "Ranger Sequoia Replacer 1.1",
    "Crossbows of the Commonwealth 1.4",
    "Dak's Throwables",
    "Explosives Expanded",
    "Remote Explosives - Standard ESP",
    "Tactical Reload Framework",
    "CALIBER-COMPLEX",
    "Special Rings",
    # 8) Settlement, Environment, & Patches
    "Clean My Settlement Redux - NextGen REBUILT",
    "Sanctuary Estates",
    "Fusion City Rising v.1.0",
    "Generator Fixerupper",
    "Better Generators (x3)",
    "Very Small Generators (1000)",
    "Deployable Turret Pack 2",
    "Scrap scrap 1.1",
    "Weapons Level List Patches"
]

with open('mod_manager/mod_data.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for idx, mod in enumerate(preferred_order):
    if mod in data:
        data[mod]['priority'] = idx
    else:
        print(f"Warning: '{mod}' not found in mod_data.json")

with open('mod_manager/mod_data.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2)

print("Priorities updated!")
