"""Unit tests for signal collectors that don't go through the full engine.
AAF integrity + multi-owner detection get direct coverage here since they're
the newest, most safety-critical signals (they drive an --apply-able ini
patch and point at a real load-order collision)."""
from helpers import make_mod_folder

from mod_manager.diagnostics import signals


def test_collect_aaf_integrity_detects_use_signatures_true(patch_config):
    make_mod_folder(
        patch_config.mods,
        "Advanced Animation Framework",
        {"xmlutility.ini": b"[Settings]\nUseSignatures=true\n"},
    )

    sig = signals.collect_aaf_integrity(patch_config.mods)
    assert sig.use_signatures_enabled is True


def test_collect_aaf_integrity_detects_use_signatures_false(patch_config):
    make_mod_folder(
        patch_config.mods,
        "Advanced Animation Framework",
        {"xmlutility.ini": b"[Settings]\nUseSignatures=false\n"},
    )

    sig = signals.collect_aaf_integrity(patch_config.mods)
    assert sig.use_signatures_enabled is False


def test_collect_aaf_integrity_none_when_key_absent(patch_config):
    make_mod_folder(
        patch_config.mods,
        "Advanced Animation Framework",
        {"xmlutility.ini": b"[Settings]\nSomeOtherKey=1\n"},
    )

    sig = signals.collect_aaf_integrity(patch_config.mods)
    assert sig.use_signatures_enabled is None


def test_collect_aaf_integrity_flags_schema_missing(patch_config):
    make_mod_folder(patch_config.mods, "Advanced Animation Framework", {})

    sig = signals.collect_aaf_integrity(patch_config.mods)
    assert sig.schema_missing is True


def test_collect_aaf_integrity_schema_present_at_mod_root(patch_config):
    make_mod_folder(
        patch_config.mods,
        "Advanced Animation Framework",
        {"aaf.xsd": b"<xsd/>"},
    )

    sig = signals.collect_aaf_integrity(patch_config.mods)
    assert sig.schema_missing is False


def test_collect_aaf_integrity_schema_present_under_aaf_subfolder(patch_config):
    make_mod_folder(
        patch_config.mods,
        "Advanced Animation Framework",
        {"AAF/aaf.xsd": b"<xsd/>"},
    )

    sig = signals.collect_aaf_integrity(patch_config.mods)
    assert sig.schema_missing is False


def test_collect_aaf_integrity_finds_zero_byte_xml_across_mods(patch_config):
    make_mod_folder(
        patch_config.mods,
        "Atomic Lust",
        {"AAF/Atomic Lust_positionData.xml": b""},
    )
    make_mod_folder(
        patch_config.mods,
        "BodyTalk2",
        {"AAF/BodyTalk2_morphSetData.xml": b"<data/>"},  # non-empty: should NOT be flagged
    )

    sig = signals.collect_aaf_integrity(patch_config.mods)
    assert sig.zero_byte_xml_files == ["Atomic Lust/AAF/Atomic Lust_positionData.xml"]


def test_find_aaf_multi_owner_files_detects_real_collision(patch_config):
    # Reproduces the actual confirmed scenario: two mods both ship
    # AAF/Atomic Lust_mfgSetData.xml; Overwrite Mod is listed with HIGHER MO2
    # priority (bottom of modlist.txt) so it wins the collision.
    make_mod_folder(
        patch_config.mods,
        "Atomic Lust",
        {"AAF/Atomic Lust_mfgSetData.xml": b"<data>real content</data>"},
    )
    make_mod_folder(
        patch_config.mods,
        "Overwrite Mod",
        {"AAF/Atomic Lust_mfgSetData.xml": b""},
    )
    patch_config.modlist.parent.mkdir(parents=True, exist_ok=True)
    patch_config.modlist.write_text(
        "# This file was automatically generated by Mod Organizer.\n"
        "+Overwrite Mod\n"
        "+Atomic Lust\n",
        encoding="utf-8",
    )

    collisions = signals.find_aaf_multi_owner_files(patch_config.mods, patch_config.modlist)
    assert len(collisions) == 1
    collision = collisions[0]
    assert collision.relative_path == "AAF/Atomic Lust_mfgSetData.xml"
    assert sorted(collision.owning_mods) == ["Atomic Lust", "Overwrite Mod"]
    assert collision.current_winner == "Overwrite Mod"


def test_find_aaf_multi_owner_files_ignores_single_owner_files(patch_config):
    make_mod_folder(
        patch_config.mods,
        "Atomic Lust",
        {"AAF/Atomic Lust_positionData.xml": b"<data/>"},
    )

    collisions = signals.find_aaf_multi_owner_files(patch_config.mods, patch_config.modlist)
    assert collisions == []
