from mod_manager.core import config, loadorder_io


def test_write_modlist_reverses_low_to_high_and_prefixes(patch_config):
    ordered = ["Foundation Mod", "Patch Mod"]
    mod_data = {
        "Foundation Mod": {"enabled": True},
        "Patch Mod": {"enabled": False},
    }
    loadorder_io.write_modlist(ordered, mod_data, backup=False)

    lines = config.MO2_MODLIST.read_text(encoding="utf-8").splitlines()
    # header, then highest priority (last in low->high) FIRST
    assert lines[0].startswith("#")
    assert lines[1] == "-Patch Mod"
    assert lines[2] == "+Foundation Mod"


def test_write_modlist_preserves_star_lines(patch_config):
    config.MO2_MODLIST.parent.mkdir(parents=True, exist_ok=True)
    config.MO2_MODLIST.write_text(
        "# This file was automatically generated by Mod Organizer.\n"
        "*DLCCoast.esm\n"
        "*DLCRobot.esm\n",
        encoding="utf-8",
    )
    loadorder_io.write_modlist(["A"], {"A": {"enabled": True}}, backup=False)
    text = config.MO2_MODLIST.read_text(encoding="utf-8")
    assert "*DLCCoast.esm" in text
    assert "*DLCRobot.esm" in text


def test_write_modlist_skips_mods_not_in_mod_data(patch_config):
    loadorder_io.write_modlist(["A", "B"], {"A": {"enabled": True}}, backup=False)
    text = config.MO2_MODLIST.read_text(encoding="utf-8")
    assert "+A" in text
    assert "B" not in text


def test_read_enabled_state_round_trips(patch_config):
    loadorder_io.write_modlist(
        ["A", "B"], {"A": {"enabled": True}, "B": {"enabled": False}}, backup=False
    )
    state = loadorder_io.read_enabled_state(config.MO2_MODLIST)
    assert state == {"A": True, "B": False}


def test_backup_rotation_caps_at_backup_keep(patch_config, monkeypatch):
    monkeypatch.setattr(config, "BACKUP_KEEP", 3)
    loadorder_io.write_modlist(["A"], {"A": {"enabled": True}}, backup=False)
    for _ in range(6):
        loadorder_io.write_modlist(["A"], {"A": {"enabled": True}}, backup=True)
    backups = list(config.BACKUP_DIR.glob("modlist.txt.*.bak"))
    assert len(backups) <= 3
