"""Canonical mod catalog -- the ONE ordering and categorization table.

Generated by reconciling the five legacy scripts against each other and
against the live mod_manager/mod_data.json (see MIGRATION_NOTES.md for the
forensic detail and the reconciliation script's output). Do not hand-edit
the data tables below without re-running that reconciliation -- a single
typo'd mod name here silently drops a mod to the back of the load order
with no error, which is the exact failure class this file exists to end.

Provenance:
- ORDER_LOW_TO_HIGH: apply_optimal_load_order.py's list, verified byte-for-byte
  identical (as a set) to align_mods_compatibility.py's list. 100 entries.
- CATEGORY / TIER assignment: server.py's tier_names/tier_mods table, verified
  to reproduce the live mod_manager/mod_data.json category for all 96
  currently-installed mods with zero mismatches. apply_optimal_load_order.py's
  categorize() function used a DIFFERENT, incompatible taxonomy that was never
  actually persisted anywhere -- it is kept here only as CATEGORY_HINTS, a
  fallback for mods that match no explicit tier entry (previously silently
  dumped into "Other" with no recourse).
- DISABLE_IF_PRESENT: identical across every legacy script that defined it.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from functools import lru_cache

# ---------------------------------------------------------------------------
# Canonical top-to-bottom guide order (index 0 = lowest priority / foundation,
# last index = highest priority / wins conflicts). This is a *known-mods*
# catalog, not the live install list -- a mod can be in here and not
# currently installed (kept for when it's reinstalled), and a currently
# installed mod not in here gets appended after everything, sorted by name
# (see order_index()).
# ---------------------------------------------------------------------------
ORDER_LOW_TO_HIGH: list[str] = [
    'Address Library - All In One',
    'Address Library',
    'Buffout 4',
    'Unofficial Fallout 4 Patch',
    'Mod Configuration Menu 1.11.221',
    'Mod Configuration Menu 1.43',
    'Advanced Animation Framework',
    'ZeX - ZaZ Extended Skeleton',
    'BodySlide and Outfit Studio -',
    "Caliente's Beautiful Bodies Enhancer -CBBE-",
    'BodyTalk',
    'Atomic Muscle',
    'Sam BodySlide Output',
    'MTM 3B OCBP - OCBPC Physics and Collision Preset',
    'Toned and Shapely Body for CBBE and 3BA Vagina Add-on',
    'RealVagCBBE',
    'Muscular Body',
    'ADDON_Body_Textures_With_Detailed_Vagina',
    'Younger Male Face Texture',
    'BodyTriangleEnhancer',
    'High Res DLC Black Face Fix',
    'Beautiful Female Settlers',
    'Beautiful Female Enemies V. 2.0',
    'MyCleanRaiders_CBBE1.0',
    'Lots More Male Hairstyles v. 1.21 - Fix',
    'Lots More Female Hairstyles v. 1.33',
    'Ponytail Hairstyles by Azar - BA2',
    'Looks Menu Customization Compendium',
    'LooksMenu v1-7-0-3',
    'LooksMenu v1-7-0-2',
    'SexAttributes',
    'AAF_FamilyPlanningEnhanced_',
    'AAF_SEU_V',
    'AAF_SCRS',
    'AAF - The One Patch to Bang Them All',
    'Atomic Lust',
    'AAF Vanilla-Kinky-Creatures Sex Animation Themes',
    'Four-Play Animations by Crazy6987',
    'FO4 Animations by Leito',
    'Animated_Fannies__',
    'SavageCabbages Animation Pack',
    'BP70 Fallout 4 Sex Animations 2.3',
    'SAM Enhanced Animations',
    'RZF4S_',
    'Dynamic Cumshots',
    'CumOverlays v',
    'Patch for animations (SquirtCum Effects, cum overlays, stages, fixes) 11.0',
    'Extended AAF Patch',
    'Ultimate AAF Patch',
    'AAF patches for Leito and Crazy animations',
    'Commonwealth Moisturizer',
    'LLFP',
    'Nude Male Cut Erect',
    'Hookers of the Commonwealth (HotC) - v.0.99h',
    'NanoSuit',
    'Black and Red Vaultsuit_FULL_Male and Female',
    'Black Road Leathers',
    'Cronen Squall - Main',
    'JensenArmor',
    'Stealth Glasses',
    'File C - HN66_SiriusArmor_3.20_Main mod files',
    'Tactical Reload Framework',
    'CALIBER-COMPLEX',
    'AS Vektor Commonwealth Version',
    'RU556 - Assault Rifle',
    'Smith and Wesson 500- REDUX beta',
    'Combined Arms - 1.0',
    'Accuracy International AX50',
    'Tavor X95',
    'MG42',
    'FN P90',
    'Bolt Actions of the Wasteland',
    'HK G11 K2',
    'Mk 23 SOCOM - 1.0 - MAIN',
    '1. SR-25 - Main CN',
    'FACTOR ENG (FULL)',
    '155mm Howitzer M1 4K New',
    '2. Glock family - Main NO TR',
    'Scar Family - Main NO TR',
    'Desert Eagle',
    'Desert Eagle Silencer 1.4',
    'R8 Revolver 4K',
    'Remington 700',
    'Kendall Ballistics Karma',
    'Stahl Arms STA-20 10mm Pistol',
    'Ranger Sequoia Replacer 1.1',
    'Crossbows of the Commonwealth 1.4',
    "Dak's Throwables",
    'Explosives Expanded',
    'Remote Explosives - Standard ESP',
    'Special Rings',
    'Clean My Settlement Redux - NextGen REBUILT',
    'Sanctuary Estates',
    'Fusion City Rising v.1.0',
    'Generator Fixerupper',
    'Better Generators (x3)',
    'Very Small Generators (1000)',
    'Deployable Turret Pack 2',
    'Scrap scrap 1.1',
    'Weapons Level List Patches',
]

_ORDER_INDEX: dict[str, int] = {name: i for i, name in enumerate(ORDER_LOW_TO_HIGH)}

# Prefer the newer / Next-Gen replacement; disable the older duplicate when
# both are installed. Identical in every legacy script that had this table.
DISABLE_IF_PRESENT: dict[str, str] = {
    'LooksMenu v1-7-0-2': 'LooksMenu v1-7-0-3',
    'Mod Configuration Menu 1.43': 'Mod Configuration Menu 1.11.221',
    'Address Library': 'Address Library - All In One',
}

# ---------------------------------------------------------------------------
# Category / tier table -- exact normalized-name matching, same algorithm as
# server.py's get_tier(). tier_names[i] is the label for tier_mods[i]; any
# mod that matches nothing falls to tier index len(TIER_MODS) == "Other".
# ---------------------------------------------------------------------------
TIER_NAMES: list[str] = [
    'Master Files (.esm)',
    'Unmanaged Mods',
    'Core Fixes & Frameworks',
    'Body & Physics Foundation',
    'Appearance / NPC Overhauls',
    'Animation Frameworks',
    'Body Talk & Physics Actors',
    'Adult Content & Animation Packs',
    'World / NPC Mods',
    'Clothing & Armor',
    'Weapons',
    'Settlements & World Edits',
    'Other',
]

TIER_MODS: list[list[str]] = [
    [],
    [],
    ['unofficial fallout 4 patch', 'mod configuration menu 1.11.221', 'zex - zaz extended skeleton', 'bodyslide and outfit studio -', 'address library - all in one'],
    ["caliente's beautiful bodies enhancer -cbbe-", 'sam bodyslide output', 'mtm 3b ocbp - ocbpc physics and collision preset', 'toned and shapely body for cbbe and 3ba vagina add-on', 'realvagcbbe', 'muscular body', 'addon_body_textures_with_detailed_vagina'],
    ['younger male face texture', 'bodytriangleenhancer', 'beautiful female settlers', 'beautiful female enemies v. 2.0', 'mycleanraiders_cbbe1.0', 'lots more male hairstyles v. 1.21 - fix', 'lots more female hairstyles v. 1.33', 'ponytail hairstyles by azar - ba2', 'looks menu customization compendium', 'looksmenu v1-7-0-3'],
    ['advanced animation framework', 'sexattributes', 'aaf_familyplanningenhanced_', 'aaf_seu_v', 'aaf_scrs', 'aaf - the one patch to bang them all', 'extended aaf patch', 'ultimate aaf patch'],
    ['bodytalk', 'buffout 4'],
    ['atomic lust', 'aaf vanilla-kinky-creatures sex animation themes', 'four-play animations by crazy6987', 'animated_fannies__', 'fo4 animations by leito', 'aaf patches for leito and crazy animations', 'savagecabbages animation pack', 'bp70 fallout 4 sex animations 2.3', 'sam enhanced animations', 'rzf4s_', 'dynamic cumshots', 'cumoverlays v', 'patch for animations (squirtcum effects, cum overlays, stages, fixes) 11.0'],
    ['commonwealth moisturizer', 'hookers of the commonwealth (hotc) - v.0.99h', 'llfp', 'nude male cut erect', 'atomic muscle'],
    ['nanosuit', 'black and red vaultsuit_full_male and female', 'black road leathers', 'cronen squall - main', 'jensenarmor', 'stealth glasses'],
    ['as vektor commonwealth version', 'ru556 - assault rifle', 'smith and wesson 500- redux beta', 'combined arms - 1.0', 'accuracy international ax50', 'tavor x95', 'mg42', 'fn p90', 'bolt actions of the wasteland', 'hk g11 k2', 'mk 23 socom - 1.0 - main', '1. sr-25 - main cn', 'factor eng (full)', '155mm howitzer m1 4k new', 'tactical reload framework', 'caliber-complex', 'special rings'],
    ['clean my settlement redux - nextgen rebuilt', 'sanctuary estates', 'fusion city rising v.1.0', 'generator fixerupper', 'better generators (x3)', 'very small generators (1000)', 'deployable turret pack 2', 'scrap scrap 1.1'],
]

OTHER_TIER_INDEX = len(TIER_MODS)  # == len(TIER_NAMES) - 1
OTHER_CATEGORY = TIER_NAMES[OTHER_TIER_INDEX]

# Fallback keyword categorizer, used ONLY when a mod matches no TIER_MODS
# entry -- i.e. it would otherwise land in "Other" with no further recourse.
# This is apply_optimal_load_order.py's categorize() table; it was never the
# thing actually persisted to disk (server.py's tier table was), so it is
# demoted to a fallback rather than promoted to primary, to avoid silently
# recategorizing the 84 mods where the two taxonomies disagree.
CATEGORY_HINTS: list[tuple[str, str]] = [
    ('address library', 'Core Frameworks & Engine Fixes'),
    ('buffout', 'Core Frameworks & Engine Fixes'),
    ('unofficial fallout 4 patch', 'Core Frameworks & Engine Fixes'),
    ('mod configuration menu', 'Core Frameworks & Engine Fixes'),
    ('advanced animation framework', 'Animation & Body Frameworks'),
    ('zex', 'Animation & Body Frameworks'),
    ('bodyslide', 'Animation & Body Frameworks'),
    ('cbbe', 'Body Frameworks & Physics'),
    ('bodytalk', 'Body Frameworks & Physics'),
    ('atomic muscle', 'Body Frameworks & Physics'),
    ('ocbp', 'Body Frameworks & Physics'),
    ('realvag', 'Textures, Skins, & Face Morphs'),
    ('muscular', 'Textures, Skins, & Face Morphs'),
    ('texture', 'Textures, Skins, & Face Morphs'),
    ('bodytriangle', 'Textures, Skins, & Face Morphs'),
    ('black face fix', 'Textures, Skins, & Face Morphs'),
    ('looksmenu', 'NPC Changes & Hair'),
    ('hairstyle', 'NPC Changes & Hair'),
    ('beautiful female', 'NPC Changes & Hair'),
    ('aaf', 'AAF Theme Packs & Adult Frameworks'),
    ('atomic lust', 'AAF Theme Packs & Adult Frameworks'),
    ('animation', 'AAF Theme Packs & Adult Frameworks'),
    ('cum', 'AAF Theme Packs & Adult Frameworks'),
    ('hotc', 'AAF Theme Packs & Adult Frameworks'),
    ('hookers of the commonwealth', 'AAF Theme Packs & Adult Frameworks'),
    ('weapon', 'Armor, Clothing, & Weapons'),
    ('rifle', 'Armor, Clothing, & Weapons'),
    ('revolver', 'Armor, Clothing, & Weapons'),
    ('caliber', 'Armor, Clothing, & Weapons'),
    ('tactical reload', 'Armor, Clothing, & Weapons'),
    ('armor', 'Armor, Clothing, & Weapons'),
    ('suit', 'Armor, Clothing, & Weapons'),
    ('generator', 'Settlement, Environment, & Patches'),
    ('settlement', 'Settlement, Environment, & Patches'),
    ('scrap', 'Settlement, Environment, & Patches'),
    ('turret', 'Settlement, Environment, & Patches'),
    ('fusion city', 'Settlement, Environment, & Patches'),
    ('sanctuary', 'Settlement, Environment, & Patches'),
    ('level list', 'Settlement, Environment, & Patches'),
]


@lru_cache(maxsize=None)
def normalize(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", name.lower())


_NORMALIZED_TIER_MODS: list[dict[str, None]] = [
    {normalize(n): None for n in group} for group in TIER_MODS
]


def order_index(name: str) -> int:
    """Priority sort key: lower = earlier / foundation, higher = later / wins.

    Mods not in the canonical order are pushed after all known mods, ordered
    alphabetically among themselves (stable, not "silently first").
    """
    if name in _ORDER_INDEX:
        return _ORDER_INDEX[name]
    return len(ORDER_LOW_TO_HIGH) + 1_000_000  # caller should still sort by name as tiebreak


def get_category_and_tier(name: str) -> tuple[str, int]:
    """Reproduce server.py's get_tier() matching exactly, then fall back to
    keyword hints instead of dropping straight to "Other".
    """
    norm = normalize(name)
    for tier_idx, group in enumerate(_NORMALIZED_TIER_MODS):
        if norm in group:
            return TIER_NAMES[tier_idx], tier_idx

    low = name.lower()
    for needle, cat in CATEGORY_HINTS:
        if needle in low:
            # Map the fallback category name to the closest tier index by
            # searching TIER_NAMES for an exact match; if the fallback
            # taxonomy has no equivalent tier, keep the fallback category
            # string but file it at the "Other" tier position so ordering
            # is still deterministic.
            try:
                return cat, TIER_NAMES.index(cat)
            except ValueError:
                return cat, OTHER_TIER_INDEX

    return OTHER_CATEGORY, OTHER_TIER_INDEX


@dataclass(frozen=True)
class CatalogEntry:
    name: str
    category: str
    tier: int
    order: int


def build_catalog(installed: set[str]) -> list[CatalogEntry]:
    """Full catalog entry for every installed mod, canonically ordered."""
    entries = []
    for name in installed:
        category, tier = get_category_and_tier(name)
        entries.append(CatalogEntry(name=name, category=category, tier=tier, order=order_index(name)))
    entries.sort(key=lambda e: (e.order, e.name))
    return entries
