"""The ONE read/write path for MO2's modlist.txt and plugins.txt.

Replaces five independent implementations (main.py, mod_manager_gui.py,
apply_optimal_load_order.py, align_mods_compatibility.py, and both
fix_aaf_alignment*.py) that each backed up to a DIFFERENT hardcoded filename
(.bak_before_optimal, .bak_align_v2, .bak_aaf_force, .bak_before_compat_align,
.bak_before_force_align) with no rotation. Running two of those scripts back
to back overwrites your only backup of the state before the FIRST one ran --
there is no way to get back more than one step. This module writes timestamped,
rotating backups to a single backups/ directory instead.

Also standardizes on one enable/disable + star-line convention:
- MO2 puts the highest-conflict-priority mod at the TOP of modlist.txt.
- This project's internal ordering is low-to-high (foundation first, patches
  last) everywhere else, so writing always reverses.
- Lines starting with '*' (DLC / Creation Club / unmanaged mods MO2 tracks
  itself) are read from the existing file and always preserved verbatim.
"""
from __future__ import annotations

import datetime as _dt
import shutil
from pathlib import Path

from . import config


def _rotate_backup(path: Path) -> Path | None:
    """Copy path into config.BACKUP_DIR with a timestamp, then prune old ones.

    Returns the backup path, or None if the source doesn't exist yet.
    """
    if not path.exists():
        return None
    config.BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    # Microsecond resolution: two writes inside the same second (a tight
    # loop, or a script that calls apply() twice in a row) must not collide
    # and silently overwrite each other's backup -- that defeats the entire
    # point of rotating backups instead of one fixed filename.
    stamp = _dt.datetime.now().strftime("%Y%m%dT%H%M%S.%f")
    backup_path = config.BACKUP_DIR / f"{path.name}.{stamp}.bak"
    shutil.copy2(path, backup_path)

    # Prune: keep the newest BACKUP_KEEP backups *for this filename*.
    siblings = sorted(
        config.BACKUP_DIR.glob(f"{path.name}.*.bak"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    for stale in siblings[config.BACKUP_KEEP :]:
        stale.unlink(missing_ok=True)

    return backup_path


def read_star_lines(modlist_path: Path | None = None) -> list[str]:
    modlist_path = modlist_path or config.MO2_MODLIST
    if not modlist_path.exists():
        return []
    return [
        line
        for line in modlist_path.read_text(encoding="utf-8").splitlines()
        if line.startswith("*")
    ]


def read_enabled_state(modlist_path: Path | None = None) -> dict[str, bool]:
    modlist_path = modlist_path or config.MO2_MODLIST
    state: dict[str, bool] = {}
    if not modlist_path.exists():
        return state
    for line in modlist_path.read_text(encoding="utf-8").splitlines():
        if line[:1] in ("+", "-") and len(line) > 1:
            state[line[1:]] = line[0] == "+"
    return state


def write_modlist(
    ordered_low_to_high: list[str],
    mod_data: dict,
    *,
    modlist_path: Path | None = None,
    backup: bool = True,
) -> Path | None:
    """Write modlist.txt. Highest priority (last in ordered_low_to_high) goes
    first in the file, per MO2's convention. Returns the backup path taken
    before writing, if any.
    """
    modlist_path = modlist_path or config.MO2_MODLIST
    stars = read_star_lines(modlist_path)
    backup_path = _rotate_backup(modlist_path) if backup else None

    lines = ["# This file was automatically generated by Mod Organizer."]
    for name in reversed(ordered_low_to_high):
        if name not in mod_data:
            continue
        enabled = mod_data[name].get("enabled", True)
        lines.append(f"{'+' if enabled else '-'}{name}")
    lines.extend(stars)

    modlist_path.parent.mkdir(parents=True, exist_ok=True)
    modlist_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return backup_path


def read_plugins(plugins_path: Path | None = None) -> list[tuple[str, bool]]:
    plugins_path = plugins_path or config.MO2_PLUGINS
    if not plugins_path.exists():
        return []
    out = []
    for line in plugins_path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        active = line.startswith("*")
        out.append((line[1:] if active else line, active))
    return out
